# Generated by Django 3.1.5 on 2021-01-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackUpCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_copy', models.CharField(max_length=45)),
                ('type_of_copy', models.CharField(max_length=45)),
                ('creation_date', models.DateField()),
                ('commentary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='paid_receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_receipt', models.IntegerField()),
                ('payment', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
                ('payment_term', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('settlment', models.CharField(max_length=45)),
                ('cost_per_minute', models.FloatField()),
                ('preferential_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=45)),
                ('number', models.CharField(max_length=45)),
                ('call_duration', models.FloatField()),
                ('id_conversation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('id_receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.receipt')),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.client')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='id_conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.telephoneconversation'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='id_receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.paid_receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='settlment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.tariff'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.receipt'),
        ),
    ]
