# Generated by Django 3.1.5 on 2021-01-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDCCompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_receipt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.receipt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id_conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.telephoneconversation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id_receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.paid_receipt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='settlment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.tariff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id_receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.receipt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.client'),
            preserve_default=False,
        ),
    ]
