# Generated by Django 3.1.5 on 2021-01-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDCCompany', '0002_auto_20210112_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid_receipt',
            name='payment',
            field=models.CharField(max_length=45),
        ),
    ]
