# Generated by Django 3.1.5 on 2021-01-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LDCCompany', '0003_auto_20210112_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='id_conversation',
            new_name='id_Tconversation',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='id_receipt',
            new_name='id_paid',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='settlment',
            new_name='id_tariff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='id_client',
        ),
    ]
