# Generated by Django 3.1.5 on 2021-01-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDCCompany', '0004_auto_20210113_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='id_Tconversation',
            new_name='id_tconversation',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='id_paid',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='number',
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='paid_receipt',
        ),
    ]
