# Generated by Django 3.1.5 on 2021-01-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LDCCompany', '0005_auto_20210117_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telephoneconversation',
            name='id_conversation',
        ),
    ]
