# Generated by Django 3.1.5 on 2021-01-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDCCompany', '0007_auto_20210119_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.client'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id_tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.tariff'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id_tconversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.telephoneconversation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDCCompany.receipt'),
        ),
    ]
